### ISSUE TITLE
Troubleshooting test dataset filtering and NA treatment

### ISSUE THREAD

**Issue by gghill** [gghill/Aquaculture-database-processing#9]
Most recent [commit](https://github.com/gghill/Aquaculture-database-processing/commit/22374301b0edc84aa5c7f9c18ac878951b74d3b7) requires attention to get the test dataset up and running prior to the next full test. I am unsure whether one error in particular is a true failure of the query or a problem with the test dataset itself.

- [x] determine the source of Siganus guttatus problem
- [ ] remove NAs from last row of any run

**Comment by almackintosh** [comment]
Removed space after Siganus guttatus in txt file so S. guttatus returns temperature values. Still need to look into removing last row of NA values

**Comment by gghill** [comment]
It seems like we've put down make_niches() for now in favor of visualization and climate analogs. We are still able to make many niches at once if Mark or anyone requests as a means of comparison. Are there still NA issues though? @almackintosh
